language: node_js

node_js:
  - '9.10.1'

sudo: false

notifications:
  email: false

branches:
  only:
  - master
  - development

install:
  - npm install

script:
  - npm run lint
  - npm run build:all
